- name: Stop Ubuntu Automatic Updates
  hosts: all
  become: yes
  tasks:
    - name: Stop the unattended-upgrades service
      service:
        name: unattended-upgrades
        state: stopped
        enabled: no

    - name: Ensure the unattended-upgrades service is disabled
      systemd:
        name: unattended-upgrades
        state: stopped
        enabled: no

    - name: Remove unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: absent

    - name: Disable update-motd-updates
      lineinfile:
        path: /etc/default/motd-news
        regexp: '^ENABLED='
        line: 'ENABLED=0'
        create: yes

    - name: Ensure no automatic updates configuration is left
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Update-Package-Lists "1";'
        replace: 'APT::Periodic::Update-Package-Lists "0";'
        backup: yes

    - name: Ensure unattended-upgrades configuration is disabled
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Unattended-Upgrade "1";'
        replace: 'APT::Periodic::Unattended-Upgrade "0";'
        backup: yes

  handlers:
    - name: Restart apt-daily.timer
      systemd:
        name: apt-daily.timer
        state: restarted

    - name: Restart apt-daily-upgrade.timer
      systemd:
        name: apt-daily-upgrade.timer
        state: restarted